name: Build and Deploy

on:
  workflow_call:
    inputs:
      env-name:
        type: string # self-hosted runner label
      github-env:
        type: string # dev or prod

jobs:
  deploy:
    runs-on: [self-hosted, '${{ inputs.env-name }}']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .env from environment variables
        run: |
          echo "APP_MESSAGE_PREFIX=${{ vars.APP_MESSAGE_PREFIX }}" >> .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=${{ vars.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_SYNC=${{ vars.DB_SYNC }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRES_IN=${{ vars.JWT_EXPIRES_IN }}" >> .env

      - name: Build Docker image
        run: docker build -t task-manager-api .

      - name: Start Postgres container
        run: docker compose -f docker-compose.yml up -d postgres

      - name: Start app container
        run: |
          docker run -d \
            --name task-manager-api \
            --env-file .env \
            --network host \
            task-manager-api

      - name: Run TypeORM migrations inside container
        run: docker exec -i task-manager-api npm run migration:run

      - name: Restart app container
        run: |
          docker restart task-manager-api
