name: Build and Deploy

on:
  workflow_call:
    inputs:
      env-name:
        type: string
      github-env:
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, '${{ inputs.env-name }}']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export environment variables
        run: |
          export APP_MESSAGE_PREFIX="${{ vars.APP_MESSAGE_PREFIX }}"
          export DB_HOST="${{ vars.DB_HOST }}"
          export DB_PORT="${{ vars.DB_PORT }}"
          export DB_USER="${{ vars.DB_USER }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_DATABASE="${{ vars.DB_DATABASE }}"
          export DB_SYNC="${{ vars.DB_SYNC }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
          export JWT_EXPIRES_IN="${{ vars.JWT_EXPIRES_IN }}"
          # show them for debug (optional)
          env | grep DB_
        shell: bash

      - name: Stop existing containers
        run: docker compose down || true

      - name: Build and start services
        run: docker compose up -d --build
