name: Dev Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      env-name: dev
      db-env-name: dev
      github-env: dev
    secrets: inherit
